name: Build Check
on:
  push:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6.0.1

      - uses: taiki-e/install-action@v2
        with:
          tool: zola@0.23.4

      - name: build zola and tailwind
        run: |
          npm i
          npm run build
